export const services = [
  {
    number: "01",
    name: "Developmental & Book Editing",
    description: "A comprehensive editorial review focused on structure, argument, pacing, clarity, chapter flow, reader experience, and the overall strength of the manuscript.",
    ideal: "Authors with a complete or near-complete manuscript who need expert guidance before publishing or querying.",
    deliverables: "Editorial letter, manuscript notes, structural recommendations, chapter-level guidance.",
    investment: "Starting at $2,500",
  },
  {
    number: "02",
    name: "Proofreading",
    description: "A final-stage polish for grammar, punctuation, spelling, formatting consistency, and surface-level errors before publication or submission.",
    ideal: "Writers with a finished manuscript that has already gone through editing.",
    deliverables: "Corrected manuscript, style consistency review, final proofing notes.",
    investment: "Starting at $750",
  },
  {
    number: "03",
    name: "Book & Memoir Ghostwriting",
    description: "Collaborative writing support for clients with a powerful story, message, or body of expertise who need help turning it into a compelling book.",
    ideal: "Memoir writers, founders, executives, public speakers, coaches, and thought leaders.",
    deliverables: "Interview-based development, chapter drafting, voice alignment, manuscript creation.",
    investment: "Custom engagements from $7,500",
  },
  {
    number: "04",
    name: "Manuscript Development",
    description: "Strategic support for shaping an unfinished idea, outline, partial draft, or early manuscript into a clear and compelling book framework.",
    ideal: "Writers who have the idea but need structure, direction, and an editorial roadmap.",
    deliverables: "Book concept refinement, outline development, chapter architecture, writing plan.",
    investment: "Starting at $1,500",
  },
  {
    number: "05",
    name: "Book Formatting",
    description: "Interior formatting and presentation support to prepare your manuscript for a polished reader experience.",
    ideal: "Self-publishing authors preparing for print, digital, or submission-ready files.",
    deliverables: "Interior layout guidance, formatting review, front/back matter organization.",
    investment: "Starting at $500",
  },
  {
    number: "06",
    name: "Thought Leadership & Authority Content",
    description: "Editorial strategy and writing support for professionals who want to turn expertise into essays, articles, speeches, newsletters, or authority-building content.",
    ideal: "Entrepreneurs, executives, founders, consultants, coaches, and subject matter experts.",
    deliverables: "Content strategy, article development, ghostwritten pieces, editorial calendar support.",
    investment: "Monthly retainers from $1,500",
  },
];
